% plot responses stored in data
point = data(:,1);
sd = data(:,2);
pointPlusSd = point+sd;
pointMinusSd = point-sd;

month = 1:length(data(:,1));

figure;clf;hold on;
% plot(month, point, 'k-');
% plot(month, pointPlusSd,'b--');
% plot(month, pointMinusSd,'b--');
confplot(month,point,sd);
hXLabel = xlabel('Months');
hYLabel= ylabel('');
hTitle= title('');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel hYLabel]  , ...
    'FontSize'   , 18          );
set( hTitle                    , ...
    'FontSize'   , 18          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'FontSize'    , 18, ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
